name: DocFX deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  actions: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install DocFX
        run: dotnet tool install --global docfx
      - name: Build docs
        run: docfx ./docs/docfx.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
